<?php

declare(strict_types=1);

namespace App\Tests\Command;

use App\Command\CommandInterface;
use App\Command\MoveMacroCommand;
use App\Command\RepeatCommand;
use App\Domain\ObjectInterface;
use App\Domain\Vector;
use App\Exception\CheckFuelException;
use App\Exception\RepeatThrownException;
use Exception;
use PHPUnit\Framework\TestCase;

class RepeatCommandTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->command       = $this->createMock(CommandInterface::class);
        $this->repeatCommand = new RepeatCommand($this->command);
    }

    /**
     * @throws Exception
     */
    public function testExecuteWithException(): void
    {
        $this->command->expects($this->once())
            ->method('execute')
            ->willThrowException(new Exception("The command can not be repeated"));

        $this->expectException(RepeatThrownException::class);
        $this->expectExceptionMessage('The command can not be repeated');

        $this->repeatCommand->execute();
    }

    /**
     * @throws Exception
     */
    public function testExecute(): void
    {
        $this->command->expects($this->once())
            ->method('execute');

        $this->repeatCommand->execute();
    }
}